language: python
sudo: required


python:
  - '3.6'
  - '3.5'


install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -r requirements-dev.txt

script:
    make cov
after_success:
    codecov
